export const MBTI_RESULT = [
    {
        MBTI: "ENFJ",
        DESCRIPTION: `They are noisy and want to be a popular insider. They have a natural talent for leading people and enjoy it. They like people a lot and feel alive when the other person trusts them. They are simple and mentally strong, and they like being part of a group but also have a bit of a "my way" personality. They like to spend their leisure time alone and have a personality that earns the trust of many people. They have a personality that fits well with others and are objective, intuitive, and interested in many things, so they have many dreams. They have a sense of humor and are quick-witted, and they like planning things. They try to please others and are sensitive to what others think, which can lead to getting hurt.`,
        COLOR: "#78C1F3",
    },
    {
        MBTI: "ENTJ",
        DESCRIPTION: "When it comes to team projects, they ultimately take the lead. They are not the type to rely on or depend on anyone. The only person they trust in this world is themselves. They rarely feel inferior. They dislike causing harm or being harmed and they are indifferent to other people's affairs. They dislike being told what to do and when they become cold-hearted, they become extremely cold-hearted. They tend to have a bulldozer-like personality. They have strong self-esteem. They don't empathize emotionally. Their business is their business, and your business is your business. When friends complain, they don't empathize, they find solutions. They like meeting new people, but they don't like forming deep relationships with people. They simulate everything in their head and find solutions. They are realistic and logical, but when they're alone, their imagination runs wild. When they're around a lot of people, they're a professional, but when they're alone, they're a daydreamer.",
        COLOR: "#9BE8D8",
    },
    {
        MBTI: "ENFP",
        DESCRIPTION: "They are easily distracted, thoughtful, and stubborn. They have quick wit and are passionate about things that interest them, but they are not interested in things they don't care about. They don't usually take the lead, but they get frustrated when no one else does and tend to take charge. At first, they can be reserved, but once they warm up to someone, they become chatty and outgoing. They enjoy talking and can easily get absorbed in something, but also easily lose interest in it. They are good at reacting to others and often end up being the go-to person for advice and problem-solving. They are not good at lying and tend to speak the truth. They like to set a goal of doing one thing that makes them happy each day. They enjoy talking with friends and making new ones. They experience extreme mood swings, and their emotions are written all over their face. They are spontaneous and impulsive and must do what they want to do. They don't save money well.",
        COLOR: "#FF8989",
    },
    {
        MBTI: "ENTP",
        DESCRIPTION: "It's most comfortable for them to wander alone. They have a strong sense of independence and can be greedy, have a strong ego, be stubborn, and cold-hearted. They may seem like an extrovert, but in reality, they are introverted. If someone is good to them, they will be twice as good to that person, but if they are not good to them, then they will have nothing to do with them. They enjoy going out, but also like being at home. They are capricious and have a strong ego. They have no problem expressing their thoughts straightforwardly and honestly. They are not interested in other people's business and don't care about what they think of them. They have no regrets about the past, so even if something is difficult, they get over it quickly. They are good at rationalizing and giving up, and they do what they want without thinking about the consequences. They have intense mood swings, and it shows when their mood changes around other people. They get the most healing and the most stress from people. They can clearly distinguish between people they like and people they dislike. They lack confidence. They like being alone, but crave companionship. If they're interested in something, they only focus on that, but once they get bored, they won't do it at all. They can't live a life that's restricted to a set pattern and hate repetitive work. They have to say when something is wrong. They live selfishly, but don't hate selfishness. They have moderate talent in many areas, but they're not exceptional at anything. They prioritize results over the process. They like being with people and have good social skills, but they also need alone time. They are good with their hands.",
        COLOR: "#FFD6A5",
    },
    {
        MBTI: "ESFP",
        DESCRIPTION: "Thy have a very impulsive personality and tends to show off a lot. They often act without much thought and tend to forget about things that worry them after a short while. They believe that they should do everything they want to do, but they tend to procrastinate when it's something they don't want to do. They are very stubborn and get bored when alone, always needing to do something. They dislike silence in gatherings and prefer to see people's strengths over their weaknesses. They value peace over fighting and have good social skills. They have high self-esteem and tend to think that everything revolves around them. Although they like people and socializing, they find it bothersome to leave the house.",
        COLOR: "#9681EB",
    },
    {
        MBTI: "ESFJ",
        DESCRIPTION: "They are more thorough than expected. They dislike making plans alone and having them fall apart. They enjoy drinking gatherings and pay a lot of attention to others' opinions. They like reading books and watching movies and are good at counseling and listening to others' problems. They take care of all the people around them, including friends and family. Even if they are hurt in relationships, they don't say it out of consideration for the other person. They can't stand awkwardness in public places and speak first.",
        COLOR: "#FFE4A7",
    },
    {
        MBTI: "ESTP",
        DESCRIPTION: "They get lonely easily. They have good hand skills. They have leadership qualities. They express themselves a lot. Adults like them. They enjoy meeting people outside, but they are lazy to go out. They must do everything they want to do, but if they can't, they just forget about it. They live carelessly and don't care about others' opinions. They don't get stressed easily, but they are not very proactive either - they just live their life as it is. They lack empathy a little. They are not interested in other people, and even thinking about things is bothersome to them. Without realizing it, they become the center of attention in group gatherings. They have a strong sense of self-confidence.",
        COLOR: "#45CFDD",
    },
    {
        MBTI: "ESTJ",
        DESCRIPTION: "They are stubborn, practical, rational, and direct. They have clear likes and dislikes and dislike being around too many people. Although they dislike being a leader, they do it well when necessary. They prefer learning new things over going out and having fun and don't mind being alone. They dislike fighting but hate losing a fight. They cannot stand not being able to handle tasks and are annoyed by breaking time commitments and being impulsive. They are not interested in others and only focus on themselves. They focus on one goal until it is achieved. Their personality when alone is slightly different from when with others. Everything must be in order, and plans must never be derailed. They like everything to be certain and take a leading role frequently. When someone can't do their work, they do two or three times the work instead of pointing it out. They lack empathy.",
        COLOR: "#E1AEFF",
    },
    {
        MBTI: "INFP",
        DESCRIPTION: "They are interested in personality theory and participates in many internet communities. They tend to be idealistic and have many random thoughts, including frequent delusions. They like attention but feel awkward when receiving it. If they can't do something perfectly, they won't start at all. They think about what needs to be done but don't actually do it. They talk well to strangers but are very reserved in places like school or work. They concentrate on what they like, but passion burns out quickly. They procrastinate due to laziness. They don't like to communicate, find it bothersome, and easily ignore messages. They value personal growth very highly. They dislike discussing personal issues with others when feeling depressed. They need to be alone when angry and shouldn't be bothered. They dislike something once and will continue to dislike it. They don't care much about others and are not easily trusting. They worry about what others think of them. They dislike when someone interferes with their working style. They like being alone but dislike feeling lonely. They dislike going out but enjoy it once they're out. They like to watch TV while lounging at home. They prefer to hang out with one or two people rather than many. They dislike fighting and usually sacrifice themselves. They are sensitive about relationships with others. They have strong self-love but low self-esteem. They won't initiate conversation with strangers, but can talk well if approached. They pretend to listen well to others but actually think of other things. They aren't interested in what others say and don't want to sympathize. They start with grand ideas but can't finish them. They think but don't act. They dislike being a nuisance to others. They are very picky about who they associate with and who they befriend.",
        COLOR: "#FFE7A0",
    },
    {
        MBTI: "INFJ",
        DESCRIPTION:"They have too many thoughts. They don't like starting new things or meeting new people. They are shy and observant. They smile on the outside, but swear a lot on the inside. They are a homebody, but they like to travel. They are a planner and like to get things done ahead of time. They hope the person they want to be close to comes to them first. They want attention, but they don't want to initiate it. They're really good to their people. They like to keep quiet, but sometimes they want to stand out. They need time alone to think. They like to plan things out. They like spending time with a close friend one-on-one. When they do something, they do it with all their heart, especially when it comes to art.",
        COLOR: "#AEE2FF",
    },
    {
        MBTI: "INTP",
        DESCRIPTION: "They like to keep to themselves. Being alone is the most comfortable and happy for them. They think they're awesome and often daydream. They enjoy analysis and deduction, and they think a lot. They are blunt and not good at small talk and dislike it. When they see illogical and foolish people, they get angry. They really like books, but they are too lazy to read them, so they just make a list. They have a strong desire for knowledge. They don't like humans, but they think they are interesting creatures. They often hear that they're too serious and not to fight. There aren't many people around them, but they get along really well with the ones that remain. They have rich emotions, don't talk much, and dislike things that bother them. They are extremely lazy and the king of procrastination. They really hate loud noises. They don't have emotional fluctuations and don't express their emotions well to others, but they don't really stress about it. They don't get hurt by most things and don't care if people curse at them, and they don't curse at others. They are calculating in their relationships with others and dislike having lighthearted conversations with their friends. If they start something, they have to see it through to the end. They are individualists, and if they can't do something perfectly, they won't do it. They dislike hurting others and don't have much interest in them. They have a strong sense of self and definite likes and dislikes.",
        COLOR: "#FEA1A1",
    },
    {
        MBTI: "ISTP",
        DESCRIPTION: "Everything is a hassle for them. They are dry and reserved, but talkative and playful once familiar. They dislike meeting new people and are not interested in others, so they don't talk about themselves. They enjoy solitary cultural activities and spend money unnecessarily. They prefer to save effort and like efficiency, and they have many delusions. They think they are the best and tend to read messages without replying if there's nothing to say. They don't like being part of a group and dislike showing off. They want to study many things but don't finish and procrastinate until it's too late. They are skilled at operating machinery and find it fun, and once invested, they must see it through to the end. They only do what they want until they lose interest and won't do what they don't want to do. They complete everything they're responsible for and dislike hierarchy and interference. They are outgoing with friends, but reserved with strangers. They like attention, but dislike noise and don't care if someone insults them. They are observant, but have strong preferences and lack empathy. They try not to show emotions, but still show them, and are interested in MBTI, astrology, and tarot. They don't clean.",
        COLOR: "#C1D0B5",
    },
    {
        MBTI: "ISFP",
        DESCRIPTION: "They are lazy and slow to take action. Emotionally unstable and empathetic, they procrastinate everything until the last minute. They are homebodies and tend to stay at home a lot. When at home, they become unreachable. They are considerate individualists who feel secretly relieved when plans get canceled. Although they enjoy being alone, they get tired of it quickly when meeting with others. They are quiet attention-seekers and shy attention-seekers. They think about compliments received all day. They dislike conflicts and arguments and have never filled out a diary completely. They get nervous around people and believe in finishing what they have started but eventually give up. When they become close to someone, they become outgoing. They are very self-conscious and only do what they want to do, avoiding things they don't want to do. Although they are believed to be kind, they are actually selfish. They are stubborn and prideful and don't open up easily to others. They like meeting people but dislike it at the same time. They have trouble making decisions and saying no, but yield easily. They are good at analyzing, criticizing, and judging, but don't act on these judgments. They procrastinate until the last minute, often referred to as humble, optimistic, pay close attention to human relationships, have low self-esteem, and follow the opinions and atmosphere of others. They hold complaints and grievances inside, unable to express them.",
        COLOR: "#82C3EC",
    },
    {
        MBTI: "ISFJ",
        DESCRIPTION: `They are principled. They enjoy being aware of others and taking care of them, but often feel lonely and dislike being around many people. They are an outsider in a group of insiders and an insider in a group of outsiders. They sometimes hesitate to answer the phone but eventually do. They are a lazy perfectionist and prefer to work alone rather than participate in group activities that require planning. Although they may appear boring to others, they are satisfied with their life. They have a lot of consideration and empathy for others but often feel stressed about human relationships. They have a "yes or no" mindset and appear indifferent, but they think a lot internally. They can be slightly critical and have a varying personality, sometimes introverted and other times extroverted. They are humble and give praise often but don't pay much attention to others unless they really dislike them. They are mild-mannered and will do almost anything if asked. They like planning, take notes, and remember things but don't usually appeal to others. They dislike taking the lead but enjoy receiving attention. They like being with people but also value their alone time. They pay attention to trivial things but remain cool. They are capable of having a long-term relationship.`,
        COLOR: "#62CDFF",
    },
    {
        MBTI: "ISTJ",
        DESCRIPTION: "They are principled and planned. When they travel, they make plans beforehand and dislike doing things spontaneously or breaking promises. They do not enjoy cooperating with others and prefer doing things alone, even if someone offers to help. They dislike interference in their work and opinions and are not very interested in other people. They find it difficult to talk about themselves and listen to others. They have a strong sense of responsibility and are sometimes described as lacking empathy. They are often described as stern and have a strong emotional barrier. When working on a project, they dislike getting sidetracked and must finish what they started.",
        COLOR: "#B3E5BE",
    },
    {
        MBTI: "INTJ",
        DESCRIPTION: "They enjoy being alone and dislikes social activities. However, they often take on a leadership role in group activities. They dislike crowded and noisy places, and are an extreme individualist and selfish. They like to plan their day-to-day activities in detail and are good at managing money, considering truth and principles important. They dislike being swayed by emotions and are not interested in other people, unable to empathize even when friends come to them for advice. Although they can help with problem-solving, they are not good at providing comfort. They enjoy daydreaming and interpreting things or art from different perspectives, and like chatting with others. They are good at managing relationships, but it takes them a long time to become close to someone. They have trouble remembering people's faces and names. They have a bit of an attention-seeking personality but do not express it because they are introverted. They are infinitely kind to animals and are a perfectionist. They have some attachment to certain things and have been told that they are insensitive. They are rational but also emotional and often think that their personality is strange. They are unique and special, but dislike hearing such things from others. They are indifferent to others' business.",
        COLOR: "#FCC2FC",
    },
]
